language: objective-c
osx_image: xcode9
script:
- xcodebuild clean test -project TravisExample.xcodeproj -scheme TravisExample -destination "platform=iOS Simulator, id=dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name=Generic iOS Simulator Device" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet 
