language: objective-c
osx_image: xcode9
script:
- xcodebuild clean test -project TravisExample.xcodeproj -scheme TravisExample -destination "platform=iOS Simulator,name=iPhone 5s,OS=11.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
